import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Peach Linen Midi Dress",
    price: 89,
    colorName: "Soft Peach",
    hexColor: "#F5D0C5",
    palette: "Light Spring",
  },
  {
    id: "2",
    name: "Ivory Silk Blouse",
    price: 68,
    colorName: "Warm Ivory",
    hexColor: "#FFF8F0",
    palette: "Light Spring",
  },
  {
    id: "3",
    name: "Coral Wrap Dress",
    price: 95,
    colorName: "Warm Coral",
    hexColor: "#E8846B",
    palette: "Warm Spring",
  },
  {
    id: "4",
    name: "Golden Honey Cardigan",
    price: 72,
    colorName: "Honey Gold",
    hexColor: "#D4A574",
    palette: "Warm Spring",
  },
  {
    id: "5",
    name: "Turquoise Shift Dress",
    price: 82,
    colorName: "Clear Turquoise",
    hexColor: "#3ECFCF",
    palette: "Clear Spring",
  },
  {
    id: "6",
    name: "Bright Fuchsia Top",
    price: 54,
    colorName: "Vivid Fuchsia",
    hexColor: "#E84393",
    palette: "Clear Spring",
  },
  {
    id: "7",
    name: "Lavender Chiffon Blouse",
    price: 64,
    colorName: "Powder Lavender",
    hexColor: "#D4C4E8",
    palette: "Light Summer",
  },
  {
    id: "8",
    name: "Rose Water Slip Dress",
    price: 78,
    colorName: "Dusty Rose",
    hexColor: "#E8B4C8",
    palette: "Light Summer",
  },
  {
    id: "9",
    name: "Mauve Cashmere Sweater",
    price: 118,
    colorName: "Soft Mauve",
    hexColor: "#C9A8B4",
    palette: "Soft Summer",
  },
  {
    id: "10",
    name: "Slate Blue Midi Skirt",
    price: 62,
    colorName: "Muted Slate",
    hexColor: "#8B9AAB",
    palette: "Soft Summer",
  },
  {
    id: "11",
    name: "Periwinkle A-Line Dress",
    price: 88,
    colorName: "Cool Periwinkle",
    hexColor: "#8B9FD4",
    palette: "Cool Summer",
  },
  {
    id: "12",
    name: "Berry Silk Camisole",
    price: 48,
    colorName: "Cool Berry",
    hexColor: "#9B4D7A",
    palette: "Cool Summer",
  },
  {
    id: "13",
    name: "Sage Linen Tunic",
    price: 58,
    colorName: "Muted Sage",
    hexColor: "#A8B89C",
    palette: "Soft Autumn",
  },
  {
    id: "14",
    name: "Dusty Teal Blouse",
    price: 66,
    colorName: "Soft Teal",
    hexColor: "#7A9E9A",
    palette: "Soft Autumn",
  },
  {
    id: "15",
    name: "Rust Knit Sweater",
    price: 74,
    colorName: "Warm Rust",
    hexColor: "#B85C38",
    palette: "Warm Autumn",
  },
  {
    id: "16",
    name: "Mustard Pleated Skirt",
    price: 56,
    colorName: "Golden Mustard",
    hexColor: "#C9A227",
    palette: "Warm Autumn",
  },
  {
    id: "17",
    name: "Forest Green Wrap Dress",
    price: 92,
    colorName: "Deep Forest",
    hexColor: "#2D4A3E",
    palette: "Deep Autumn",
  },
  {
    id: "18",
    name: "Burgundy Velvet Blouse",
    price: 84,
    colorName: "Rich Burgundy",
    hexColor: "#6B2D3E",
    palette: "Deep Autumn",
  },
  {
    id: "19",
    name: "Electric Blue Cocktail Dress",
    price: 110,
    colorName: "Clear Cobalt",
    hexColor: "#2563EB",
    palette: "Clear Winter",
  },
  {
    id: "20",
    name: "Hot Pink Structured Blazer",
    price: 128,
    colorName: "Vivid Magenta",
    hexColor: "#DB2777",
    palette: "Clear Winter",
  },
  {
    id: "21",
    name: "Royal Blue Silk Dress",
    price: 98,
    colorName: "Cool Royal",
    hexColor: "#1E3A8A",
    palette: "Cool Winter",
  },
  {
    id: "22",
    name: "Icy Pink Cashmere Sweater",
    price: 135,
    colorName: "Cool Rose",
    hexColor: "#F0A8C8",
    palette: "Cool Winter",
  },
  {
    id: "23",
    name: "Black Wool Coat",
    price: 189,
    colorName: "True Black",
    hexColor: "#1A1A1A",
    palette: "Deep Winter",
  },
  {
    id: "24",
    name: "Emerald Evening Gown",
    price: 165,
    colorName: "Deep Emerald",
    hexColor: "#065F46",
    palette: "Deep Winter",
  },
];
